# Generated by Django 5.2.9 on 2026-08-15 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Vereador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parlamentar', models.CharField(max_length=150, verbose_name='Nome parlamentar')),
                ('nome_civil', models.CharField(blank=True, max_length=200, verbose_name='Nome civil')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo (mandato em exercício)')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vereadores', to='parlamento.partido', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Vereador',
                'verbose_name_plural': 'Vereadores',
                'ordering': ['nome_parlamentar'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('gabinete', 'Gabinete de Vereador'), ('bancada', 'Bancada'), ('tecnico', 'Setor Técnico'), ('configurador', 'Configurador (Setor Técnico)'), ('admin', 'Administrador')], max_length=20, verbose_name='Papel')),
                ('partido', models.ForeignKey(blank=True, help_text="Preencher apenas para papel 'Bancada'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_bancada', to='parlamento.partido', verbose_name='Partido (bancada)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('vereador', models.ForeignKey(blank=True, help_text="Preencher apenas para papel 'Gabinete de Vereador'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_gabinete', to='parlamento.vereador', verbose_name='Vereador (gabinete)')),
            ],
            options={
                'verbose_name': 'Perfil de acesso',
                'verbose_name_plural': 'Perfis de acesso',
            },
        ),
        migrations.CreateModel(
            name='Bancada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ata', models.FileField(blank=True, null=True, upload_to='atas_bancada/%Y/', verbose_name='Ata de apresentação (PDF)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancadas', to='orcamento.exercicio', verbose_name='Exercício')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancadas', to='parlamento.partido', verbose_name='Partido')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancadas_coordenadas', to='parlamento.vereador', verbose_name='Coordenador(a)')),
                ('membros', models.ManyToManyField(related_name='bancadas', to='parlamento.vereador', verbose_name='Vereadores da bancada')),
            ],
            options={
                'verbose_name': 'Bancada',
                'verbose_name_plural': 'Bancadas',
                'ordering': ['exercicio', 'partido'],
                'unique_together': {('partido', 'exercicio')},
            },
        ),
    ]
