# Generated by Django 5.2.9 on 2026-08-15 17:44

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamento', '0001_initial'),
        ('parlamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, verbose_name='Nº')),
                ('codigo', models.CharField(editable=False, max_length=50, verbose_name='Código')),
                ('codigo_legado', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Código no sistema legado')),
                ('municipio', models.CharField(editable=False, max_length=100, verbose_name='Município')),
                ('modalidade', models.CharField(choices=[('individual', 'Individual'), ('coletiva', 'Bancada/Coletiva')], editable=False, max_length=12, verbose_name='Modalidade')),
                ('tipo_transferencia', models.CharField(editable=False, max_length=100, verbose_name='Tipo de Transferência')),
                ('acao_orcamentaria', models.TextField(help_text="Texto que aparece na caixa de descrição do formulário e na coluna 'Ação Orçamentária'.", verbose_name='Descrição da Emenda Impositiva Proposta')),
                ('objeto_despesa', models.TextField(verbose_name='Objeto da Despesa')),
                ('categoria_economica', models.CharField(choices=[('investimento', 'Investimento'), ('custeio', 'Custeio')], max_length=20, verbose_name='Categoria Econômica')),
                ('valor_custeio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor de Custeio (R$)')),
                ('valor_investimento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor de Investimento (R$)')),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='Valor Previsto (R$)')),
                ('documentacao_entidade', models.FileField(blank=True, null=True, upload_to='documentos_emendas/%Y/', verbose_name='Documentos da Emenda (PDF da entidade de destino)')),
                ('vinculacao_orcamentaria', models.CharField(blank=True, help_text='Classificação Funcional Programática. Ex.: 13 01. 08 244 5003 8.500', max_length=150, verbose_name='Vinculação Orçamentária')),
                ('data_reserva', models.DateField(blank=True, null=True, verbose_name='Data da reserva orçamentária')),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('em_conferencia', 'Em conferência'), ('publicada', 'Publicada'), ('devolvida', 'Devolvida para ajuste')], default='rascunho', max_length=20, verbose_name='Situação')),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_devolucao', models.TextField(blank=True, verbose_name='Motivo da devolução')),
                ('pdf_gerado', models.FileField(blank=True, null=True, upload_to='emendas/pdf/%Y/', verbose_name='PDF gerado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor_bancada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='parlamento.bancada', verbose_name='Bancada')),
                ('autor_vereador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='parlamento.vereador', verbose_name='Vereador')),
                ('conferida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendas_conferidas', to=settings.AUTH_USER_MODEL, verbose_name='Conferida por')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emendas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='orcamento.entidade', verbose_name='Entidade (OSC)')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='orcamento.exercicio', verbose_name='Exercício')),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='orcamento.faixa', verbose_name='Faixa')),
                ('funcao_governo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='orcamento.funcaogoverno', verbose_name='Função de Governo')),
                ('orgao_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='orcamento.orgaoexecutor', verbose_name='Órgão Executor')),
                ('partido', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='parlamento.partido', verbose_name='Partido Político')),
                ('programa_ppa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='orcamento.programappa', verbose_name='Programa PPA')),
                ('subfuncao_governo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='orcamento.subfuncaogoverno', verbose_name='Subfunção de Governo')),
                ('unidade_gestora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='orcamento.unidadegestora', verbose_name='Unidade Gestora Vinculada')),
            ],
            options={
                'verbose_name': 'Emenda',
                'verbose_name_plural': 'Emendas',
                'ordering': ['exercicio', 'faixa', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='EmendaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='emendas/anexos/%Y/', verbose_name='Arquivo (PDF)')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('emenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='emendas.emenda', verbose_name='Emenda')),
            ],
            options={
                'verbose_name': 'Anexo da emenda',
                'verbose_name_plural': 'Anexos da emenda',
                'ordering': ['emenda', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmenda',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, verbose_name='Nº')),
                ('codigo', models.CharField(editable=False, max_length=50, verbose_name='Código')),
                ('codigo_legado', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Código no sistema legado')),
                ('municipio', models.CharField(editable=False, max_length=100, verbose_name='Município')),
                ('modalidade', models.CharField(choices=[('individual', 'Individual'), ('coletiva', 'Bancada/Coletiva')], editable=False, max_length=12, verbose_name='Modalidade')),
                ('tipo_transferencia', models.CharField(editable=False, max_length=100, verbose_name='Tipo de Transferência')),
                ('acao_orcamentaria', models.TextField(help_text="Texto que aparece na caixa de descrição do formulário e na coluna 'Ação Orçamentária'.", verbose_name='Descrição da Emenda Impositiva Proposta')),
                ('objeto_despesa', models.TextField(verbose_name='Objeto da Despesa')),
                ('categoria_economica', models.CharField(choices=[('investimento', 'Investimento'), ('custeio', 'Custeio')], max_length=20, verbose_name='Categoria Econômica')),
                ('valor_custeio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor de Custeio (R$)')),
                ('valor_investimento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor de Investimento (R$)')),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='Valor Previsto (R$)')),
                ('documentacao_entidade', models.TextField(blank=True, max_length=100, null=True, verbose_name='Documentos da Emenda (PDF da entidade de destino)')),
                ('vinculacao_orcamentaria', models.CharField(blank=True, help_text='Classificação Funcional Programática. Ex.: 13 01. 08 244 5003 8.500', max_length=150, verbose_name='Vinculação Orçamentária')),
                ('data_reserva', models.DateField(blank=True, null=True, verbose_name='Data da reserva orçamentária')),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('em_conferencia', 'Em conferência'), ('publicada', 'Publicada'), ('devolvida', 'Devolvida para ajuste')], default='rascunho', max_length=20, verbose_name='Situação')),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_devolucao', models.TextField(blank=True, verbose_name='Motivo da devolução')),
                ('pdf_gerado', models.TextField(blank=True, max_length=100, null=True, verbose_name='PDF gerado')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor_bancada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parlamento.bancada', verbose_name='Bancada')),
                ('autor_vereador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parlamento.vereador', verbose_name='Vereador')),
                ('conferida_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Conferida por')),
                ('criada_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('entidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.entidade', verbose_name='Entidade (OSC)')),
                ('exercicio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.exercicio', verbose_name='Exercício')),
                ('faixa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.faixa', verbose_name='Faixa')),
                ('funcao_governo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.funcaogoverno', verbose_name='Função de Governo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orgao_executor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.orgaoexecutor', verbose_name='Órgão Executor')),
                ('partido', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parlamento.partido', verbose_name='Partido Político')),
                ('programa_ppa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.programappa', verbose_name='Programa PPA')),
                ('subfuncao_governo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.subfuncaogoverno', verbose_name='Subfunção de Governo')),
                ('unidade_gestora', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.unidadegestora', verbose_name='Unidade Gestora Vinculada')),
            ],
            options={
                'verbose_name': 'historical Emenda',
                'verbose_name_plural': 'historical Emendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='emenda',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('autor_bancada__isnull', True), ('autor_vereador__isnull', False)), models.Q(('autor_bancada__isnull', False), ('autor_vereador__isnull', True)), _connector='OR'), name='emenda_autor_exclusivo'),
        ),
        migrations.AlterUniqueTogether(
            name='emenda',
            unique_together={('exercicio', 'codigo'), ('exercicio', 'faixa', 'numero')},
        ),
    ]
