# Generated by Django 5.2.9 on 2026-08-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas', '0001_initial'),
        ('parlamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emenda',
            name='proponente',
            field=models.ForeignKey(blank=True, help_text='Apenas para emendas coletivas: qual vereador da bancada propôs esta emenda específica (pode ser diferente do coordenador, que só assina a ata).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendas_propostas', to='parlamento.vereador', verbose_name='Vereador proponente'),
        ),
        migrations.AddField(
            model_name='historicalemenda',
            name='proponente',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Apenas para emendas coletivas: qual vereador da bancada propôs esta emenda específica (pode ser diferente do coordenador, que só assina a ata).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parlamento.vereador', verbose_name='Vereador proponente'),
        ),
    ]
