# Generated by Django 5.2.9 on 2026-08-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas', '0002_emenda_proponente_historicalemenda_proponente'),
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emenda',
            name='acao_orcamentaria',
            field=models.TextField(help_text="O que será feito com o valor da emenda, em termos orçamentários — a atividade ou o programa que será custeado. Ex.: 'Apoio a atividades desenvolvidas pela Seaspac'. Este texto alimenta a coluna 'Ação Orçamentária' da tabela pública.", verbose_name='Ação Orçamentária'),
        ),
        migrations.AlterField(
            model_name='emenda',
            name='funcao_governo',
            field=models.ForeignKey(blank=True, help_text='Calculada automaticamente pelo setor técnico a partir da Vinculação Orçamentária.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendas', to='orcamento.funcaogoverno', verbose_name='Função de Governo'),
        ),
        migrations.AlterField(
            model_name='emenda',
            name='objeto_despesa',
            field=models.TextField(help_text="O que exatamente será adquirido, contratado ou executado com o valor da emenda — de forma específica. Ex.: 'Apoio a atividades desenvolvidas pela Seaspac na assistência a famílias em situação de vulnerabilidade social'.", verbose_name='Objeto da Despesa'),
        ),
        migrations.AlterField(
            model_name='historicalemenda',
            name='acao_orcamentaria',
            field=models.TextField(help_text="O que será feito com o valor da emenda, em termos orçamentários — a atividade ou o programa que será custeado. Ex.: 'Apoio a atividades desenvolvidas pela Seaspac'. Este texto alimenta a coluna 'Ação Orçamentária' da tabela pública.", verbose_name='Ação Orçamentária'),
        ),
        migrations.AlterField(
            model_name='historicalemenda',
            name='funcao_governo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Calculada automaticamente pelo setor técnico a partir da Vinculação Orçamentária.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.funcaogoverno', verbose_name='Função de Governo'),
        ),
        migrations.AlterField(
            model_name='historicalemenda',
            name='objeto_despesa',
            field=models.TextField(help_text="O que exatamente será adquirido, contratado ou executado com o valor da emenda — de forma específica. Ex.: 'Apoio a atividades desenvolvidas pela Seaspac na assistência a famílias em situação de vulnerabilidade social'.", verbose_name='Objeto da Despesa'),
        ),
    ]
