# Generated by Django 5.2.9 on 2026-08-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas', '0003_alter_emenda_acao_orcamentaria_and_more'),
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emenda',
            unique_together={('exercicio', 'codigo')},
        ),
        migrations.AlterField(
            model_name='emenda',
            name='codigo',
            field=models.CharField(blank=True, default=None, editable=False, help_text='Atribuído pelo sistema só na publicação, depois que o setor técnico define o Tipo de Transferência.', max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='emenda',
            name='numero',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Atribuído pelo sistema só na publicação, depois que o setor técnico define o Tipo de Transferência.', null=True, verbose_name='Nº'),
        ),
        migrations.AlterField(
            model_name='emenda',
            name='tipo_transferencia',
            field=models.CharField(blank=True, choices=[('Finalidade Definida', 'Finalidade Definida'), ('Transferência Especial', 'Transferência Especial')], help_text='Definido pelo setor técnico na conferência — usado para gerar o número/código da emenda na publicação.', max_length=100, verbose_name='Tipo de Transferência'),
        ),
        migrations.AlterField(
            model_name='historicalemenda',
            name='codigo',
            field=models.CharField(blank=True, default=None, editable=False, help_text='Atribuído pelo sistema só na publicação, depois que o setor técnico define o Tipo de Transferência.', max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='historicalemenda',
            name='numero',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Atribuído pelo sistema só na publicação, depois que o setor técnico define o Tipo de Transferência.', null=True, verbose_name='Nº'),
        ),
        migrations.AlterField(
            model_name='historicalemenda',
            name='tipo_transferencia',
            field=models.CharField(blank=True, choices=[('Finalidade Definida', 'Finalidade Definida'), ('Transferência Especial', 'Transferência Especial')], help_text='Definido pelo setor técnico na conferência — usado para gerar o número/código da emenda na publicação.', max_length=100, verbose_name='Tipo de Transferência'),
        ),
        migrations.AlterUniqueTogether(
            name='emenda',
            unique_together={('exercicio', 'codigo'), ('exercicio', 'modalidade', 'tipo_transferencia', 'numero')},
        ),
    ]
