# Generated by Django 5.2.9 on 2026-08-15 17:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('documentacao', models.FileField(blank=True, null=True, upload_to='entidades/documentacao/%Y/', verbose_name='Documentação da entidade (PDF)')),
                ('validade_documentacao', models.DateField(blank=True, null=True, verbose_name='Validade da documentação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True, verbose_name='Ano')),
                ('municipio', models.CharField(default='Marabá', max_length=100, verbose_name='Município')),
                ('rcl_exercicio_anterior', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Receita Corrente Líquida do exercício anterior (R$)')),
                ('ano_referencia_rcl', models.PositiveIntegerField(help_text='Ex.: para o exercício de 2026, a RCL é a de 2024.', verbose_name='Ano de referência da RCL')),
                ('numero_vereadores', models.PositiveIntegerField(verbose_name='Número de vereadores da Casa')),
                ('prazo_envio', models.DateField(blank=True, null=True, verbose_name='Prazo para envio das emendas')),
                ('base_legal', models.TextField(blank=True, default='Base Legal: Art. 147-A e 147-B da Lei Orgânica do Município de Marabá | Vedada destinação para pessoal.', verbose_name='Base legal (rodapé das exportações)')),
                ('observacao_legal_formulario', models.TextField(blank=True, default='Deverá ser observado o estabelecido na Lei Complementar Municipal Nº 23/2025, no que se refere à destinação das emendas impositivas.', verbose_name='Observação legal impressa no formulário (página 2)')),
                ('situacao', models.CharField(choices=[('aberto', 'Aberto'), ('encerrado', 'Encerrado')], default='aberto', max_length=10, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercício orçamentário',
                'verbose_name_plural': 'Exercícios orçamentários',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='FuncaoGoverno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem no PDF (checkbox)')),
            ],
            options={
                'verbose_name': 'Função de governo',
                'verbose_name_plural': 'Funções de governo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeGestora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('exige_documentacao_entidade', models.BooleanField(default=False, help_text="Marcar apenas para 'Entidade Privada Sem Fins Lucrativos'.", verbose_name='Exige documentação da entidade de destino')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Unidade gestora',
                'verbose_name_plural': 'Unidades gestoras',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: "Emendas Individuais 1,55%"', max_length=150, verbose_name='Nome')),
                ('modalidade', models.CharField(choices=[('individual', 'Individual'), ('coletiva', 'Bancada/Coletiva')], max_length=12, verbose_name='Modalidade')),
                ('percentual_rcl', models.DecimalField(decimal_places=4, help_text='Ex.: 1.5500 para 1,55%', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Percentual da RCL')),
                ('sigla_codigo', models.CharField(help_text='Ex.: EPIMI, EPIMB', max_length=10, verbose_name='Sigla do código')),
                ('tipo_transferencia', models.CharField(default='Finalidade Definida', max_length=100, verbose_name='Tipo de transferência')),
                ('rotulo_transferencia', models.CharField(default='FD', help_text='Coluna "RP" do PDF.', max_length=10, verbose_name='Rótulo do tipo de transferência')),
                ('percentual_minimo_outras_funcoes', models.DecimalField(blank=True, decimal_places=2, help_text='Ex.: 50.00 quando a legislação exige reservar parte do teto individual para funções fora da destinação principal. Deixe em branco se não se aplicar a esta faixa.', max_digits=5, null=True, verbose_name='Percentual mínimo para outras funções')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='orcamento.exercicio', verbose_name='Exercício')),
            ],
            options={
                'verbose_name': 'Faixa de emenda',
                'verbose_name_plural': 'Faixas de emenda',
                'ordering': ['exercicio', 'ordem', 'nome'],
                'unique_together': {('exercicio', 'sigla_codigo')},
            },
        ),
        migrations.CreateModel(
            name='ProgramaPPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do programa')),
                ('objetivos', models.TextField(verbose_name='Objetivos do programa')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_ppa', to='orcamento.exercicio', verbose_name='Exercício')),
            ],
            options={
                'verbose_name': 'Programa do PPA',
                'verbose_name_plural': 'Programas do PPA',
                'ordering': ['exercicio', 'codigo'],
                'unique_together': {('exercicio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='SubfuncaoGoverno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subfuncoes', to='orcamento.funcaogoverno', verbose_name='Função de governo')),
            ],
            options={
                'verbose_name': 'Subfunção de governo',
                'verbose_name_plural': 'Subfunções de governo',
                'ordering': ['funcao', 'nome'],
                'unique_together': {('funcao', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='OrgaoExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('unidade_gestora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orgaos', to='orcamento.unidadegestora', verbose_name='Unidade gestora')),
            ],
            options={
                'verbose_name': 'Órgão executor',
                'verbose_name_plural': 'Órgãos executores',
                'ordering': ['nome'],
                'unique_together': {('nome', 'unidade_gestora')},
            },
        ),
    ]
