# Generated by Django 5.2.9 on 2026-08-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faixa',
            name='rotulo_transferencia',
        ),
    ]
